# Generated by Django 5.2.5 on 2025-08-19 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Müşteri Adı')),
                ('kod', models.CharField(help_text='Örnek: MST001', max_length=20, unique=True, verbose_name='Müşteri Kodu')),
                ('telefon', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Ürün Kodu')),
                ('birim', models.CharField(choices=[('ADET', 'Adet'), ('KG', 'Kilogram'), ('M', 'Metre'), ('M2', 'Metrekare'), ('M3', 'Metreküp'), ('LT', 'Litre')], default='ADET', max_length=20, verbose_name='Birim')),
                ('uretim_suresi', models.PositiveIntegerField(help_text='Bir ürünün üretim süresi', verbose_name='Üretim Süresi (dakika)')),
                ('minimum_stok', models.PositiveIntegerField(default=0, verbose_name='Minimum Stok')),
                ('mevcut_stok', models.PositiveIntegerField(default=0, verbose_name='Mevcut Stok')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['ad'],
            },
        ),
    ]
