# Generated by Django 5.2.5 on 2025-08-19 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(max_length=50, unique=True)),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('teslim_tarihi', models.DateField()),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=20)),
                ('notlar', models.TextField(blank=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='production.musteri')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='SiparisKalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.IntegerField()),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notlar', models.TextField(blank=True)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='production.siparis')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.urun')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
    ]
