# Generated by Django 5.2.5 on 2025-08-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_siparis_sipariskalem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiparisDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='siparis_dosyalari/%Y/%m/')),
                ('aciklama', models.CharField(blank=True, max_length=200)),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='production.siparis')),
            ],
            options={
                'verbose_name': 'Sipariş Dosyası',
                'verbose_name_plural': 'Sipariş Dosyaları',
            },
        ),
    ]
