# Generated by Django 5.2.5 on 2025-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_siparisdosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='dosya',
            field=models.FileField(blank=True, help_text='PDF, Word, Excel veya resim dosyası ekleyebilirsiniz', null=True, upload_to='siparis_dosyalari/%Y/%m/', verbose_name='Ek Dosya'),
        ),
    ]
