# Generated by Django 5.2.5 on 2025-08-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_siparis_dosya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urun',
            options={'ordering': ['kategori', 'ad'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.RemoveField(
            model_name='urun',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='mevcut_stok',
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('hammadde', 'Hammadde'), ('ara_urun', 'Ara Ürün'), ('bitmis_urun', 'Bitmiş Ürün')], default='bitmis_urun', max_length=20),
        ),
        migrations.AddField(
            model_name='urun',
            name='stok_miktari',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urun',
            name='ad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='urun',
            name='birim',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='urun',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kod',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='minimum_stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urun',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='uretim_suresi',
            field=models.IntegerField(default=0, help_text='Dakika cinsinden'),
        ),
        migrations.CreateModel(
            name='UrunRecete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notlar', models.TextField(blank=True)),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanildigi_urunler', to='production.urun')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recete', to='production.urun')),
            ],
            options={
                'verbose_name': 'Ürün Reçetesi',
                'verbose_name_plural': 'Ürün Reçeteleri',
                'unique_together': {('urun', 'malzeme')},
            },
        ),
    ]
