# Generated by Django 5.2.5 on 2025-08-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_urun_options_remove_urun_aciklama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='uretim_suresi',
        ),
    ]
