# Generated by Django 5.2.5 on 2025-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_urun_uretim_suresi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='birim',
            field=models.CharField(choices=[('mm', 'Milimetre (mm)'), ('cm', 'Santimetre (cm)'), ('m', 'Metre (m)'), ('m2', 'Metrekare (m²)'), ('m3', 'Metreküp (m³)'), ('mg', 'Miligram (mg)'), ('gr', 'Gram (gr)'), ('kg', 'Kilogram (kg)'), ('ton', 'Ton'), ('ml', 'Mililitre (ml)'), ('lt', 'Litre (lt)'), ('adet', 'Adet'), ('paket', 'Paket'), ('koli', 'Koli'), ('deste', 'Deste'), ('düzine', 'Düzine'), ('kutu', 'Kutu'), ('torba', 'Torba'), ('rulo', 'Rulo'), ('top', 'Top'), ('levha', 'Levha'), ('tabaka', 'Tabaka'), ('çift', 'Çift'), ('takım', 'Takım'), ('set', 'Set')], default='adet', max_length=20),
        ),
    ]
