# Generated by Django 5.2.5 on 2025-08-19 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_urun_birim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='urunrecete',
            old_name='malzeme',
            new_name='hammadde',
        ),
        migrations.AlterUniqueTogether(
            name='urunrecete',
            unique_together={('urun', 'hammadde')},
        ),
        migrations.CreateModel(
            name='MalzemePlanlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=20)),
                ('onaylayan_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malzeme_planlamalari', to='production.siparis')),
            ],
            options={
                'verbose_name': 'Malzeme Planlama',
                'verbose_name_plural': 'Malzeme Planlamaları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='MalzemePlanlamaDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kaynak', models.CharField(choices=[('stok', 'Stoktan Kullanım'), ('uretim', 'Üretim'), ('satinalma', 'Satın Alma')], max_length=20)),
                ('seviye', models.IntegerField(default=0)),
                ('planlama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='production.malzemeplanlama')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.urun')),
                ('ust_urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_malzemeler', to='production.malzemeplanlamadetay')),
            ],
            options={
                'verbose_name': 'Malzeme Planlama Detayı',
                'verbose_name_plural': 'Malzeme Planlama Detayları',
                'ordering': ['seviye', 'urun__ad'],
            },
        ),
        migrations.CreateModel(
            name='SatinAlmaTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(max_length=20, unique=True)),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('teklif_aliniyor', 'Teklif Alınıyor'), ('siparis_verildi', 'Sipariş Verildi'), ('teslim_alindi', 'Teslim Alındı'), ('iptal', 'İptal')], default='beklemede', max_length=20)),
                ('tahmini_teslim_tarihi', models.DateField(blank=True, null=True)),
                ('planlama_detay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.malzemeplanlamadetay')),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'ordering': ['-talep_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='StokTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(max_length=20, unique=True)),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('karsilandi', 'Karşılandı'), ('iptal', 'İptal')], default='beklemede', max_length=20)),
                ('planlama_detay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.malzemeplanlamadetay')),
            ],
            options={
                'verbose_name': 'Stok Talebi',
                'verbose_name_plural': 'Stok Talepleri',
                'ordering': ['-talep_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='UretimTalep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uretim_no', models.CharField(max_length=20, unique=True)),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('planlandi', 'Planlandı'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='beklemede', max_length=20)),
                ('planlanan_tarih', models.DateField(blank=True, null=True)),
                ('planlama_detay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.malzemeplanlamadetay')),
            ],
            options={
                'verbose_name': 'Üretim Talebi',
                'verbose_name_plural': 'Üretim Talepleri',
                'ordering': ['-talep_tarihi'],
            },
        ),
    ]
