# Generated by Django 5.2.5 on 2025-08-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_rename_malzeme_urunrecete_hammadde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malzemeplanlamadetay',
            name='planlama',
        ),
        migrations.RemoveField(
            model_name='malzemeplanlamadetay',
            name='urun',
        ),
        migrations.RemoveField(
            model_name='malzemeplanlamadetay',
            name='ust_urun',
        ),
        migrations.RemoveField(
            model_name='satinalmatalep',
            name='planlama_detay',
        ),
        migrations.RemoveField(
            model_name='stoktalep',
            name='planlama_detay',
        ),
        migrations.RemoveField(
            model_name='uretimtalep',
            name='planlama_detay',
        ),
        migrations.RenameField(
            model_name='urunrecete',
            old_name='hammadde',
            new_name='malzeme',
        ),
        migrations.AlterUniqueTogether(
            name='urunrecete',
            unique_together={('urun', 'malzeme')},
        ),
        migrations.DeleteModel(
            name='MalzemePlanlama',
        ),
        migrations.DeleteModel(
            name='SatinAlmaTalep',
        ),
        migrations.DeleteModel(
            name='StokTalep',
        ),
        migrations.DeleteModel(
            name='MalzemePlanlamaDetay',
        ),
        migrations.DeleteModel(
            name='UretimTalep',
        ),
    ]
