# Generated by Django 5.2.5 on 2025-08-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_malzemeplanlamadetay_planlama_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalzemePlanlama',
            fields=[
            ],
            options={
                'verbose_name': 'Malzeme Planlama',
                'verbose_name_plural': 'Malzeme Planlama',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.siparis',),
        ),
        migrations.CreateModel(
            name='MalzemeIhtiyac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malzeme_adi', models.CharField(max_length=200, verbose_name='Malzeme Adı')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('birim', models.CharField(max_length=20, verbose_name='Birim')),
                ('islem_tipi', models.CharField(choices=[('satin_al', 'Satın Al'), ('stoktan_kullan', 'Stoktan Kullan')], max_length=20, verbose_name='İşlem Tipi')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('siparis_verildi', 'Sipariş Verildi'), ('kismi_geldi', 'Kısmi Geldi'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('ilgili_siparisler', models.JSONField(verbose_name='İlgili Siparişler')),
                ('ilgili_urunler', models.JSONField(verbose_name='İlgili Ürünler')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Malzeme İhtiyacı',
                'verbose_name_plural': 'Malzeme İhtiyaçları',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
