# Generated by Django 5.2.5 on 2025-08-20 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_malzemeplanlama_malzemeihtiyac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Tedarikçi Adı')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Tedarikçi Kodu')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('vergi_no', models.CharField(blank=True, max_length=20, verbose_name='Vergi No')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='SatinAlmaKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Fiyat')),
                ('malzeme_ihtiyaci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.malzemeihtiyac', verbose_name='Malzeme İhtiyacı')),
            ],
            options={
                'verbose_name': 'Satın Alma Kalemi',
                'verbose_name_plural': 'Satın Alma Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='SatinAlmaSiparisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(max_length=50, unique=True, verbose_name='Sipariş No')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('teslim_tarihi', models.DateField(verbose_name='Teslim Tarihi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Tutar')),
                ('siparis_dosyasi', models.FileField(blank=True, upload_to='satinalma_siparisleri/', verbose_name='Sipariş Dosyası')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('malzeme_ihtiyaclari', models.ManyToManyField(through='production.SatinAlmaKalemi', to='production.malzemeihtiyac', verbose_name='Malzeme İhtiyaçları')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın Alma Siparişi',
                'verbose_name_plural': 'Satın Alma Siparişleri',
                'ordering': ['-tarih'],
            },
        ),
        migrations.AddField(
            model_name='satinalmakalemi',
            name='siparis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='production.satinalmasiparisi', verbose_name='Sipariş'),
        ),
    ]
