# Generated by Django 5.2.5 on 2025-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_tedarikci_satinalmakalemi_satinalmasiparisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('malzeme_planlandi', 'Malzeme Planlaması Yapıldı'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=20),
        ),
    ]
