# Generated by Django 5.2.5 on 2025-08-20 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_siparis_durum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalmasiparisi',
            name='guncel_teslim_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Güncel Teslim Tarihi'),
        ),
        migrations.CreateModel(
            name='SatinAlmaTeslimGuncelleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_teslim_tarihi', models.DateField(verbose_name='Eski Teslim Tarihi')),
                ('yeni_teslim_tarihi', models.DateField(verbose_name='Yeni Teslim Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Güncelleme Tarihi')),
                ('guncelleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teslim_guncellemeleri', to='production.satinalmasiparisi', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Teslim Tarihi Güncellemesi',
                'verbose_name_plural': 'Teslim Tarihi Güncellemeleri',
                'ordering': ['-guncelleme_tarihi'],
            },
        ),
    ]
