# Generated by Django 5.2.5 on 2025-08-21 06:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_satinalmasiparisi_guncel_teslim_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MalzemeGelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelen_miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gelen Miktar')),
                ('gelis_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Geliş Tarihi')),
                ('irsaliye_no', models.CharField(max_length=100, verbose_name='İrsaliye No')),
                ('fatura_no', models.CharField(blank=True, max_length=100, verbose_name='Fatura No')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('kaydeden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('satinalma_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelisler', to='production.satinalmakalemi', verbose_name='Satın Alma Kalemi')),
                ('satinalma_siparisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelisler', to='production.satinalmasiparisi', verbose_name='Satın Alma Siparişi')),
            ],
            options={
                'verbose_name': 'Malzeme Geliş',
                'verbose_name_plural': 'Malzeme Gelişler',
                'ordering': ['-gelis_tarihi', '-kayit_tarihi'],
            },
        ),
    ]
