# Generated by Django 5.2.5 on 2025-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_malzemegelis'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzemegelis',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Birim Fiyat'),
        ),
        migrations.AddField(
            model_name='malzemegelis',
            name='evrak_dosyasi',
            field=models.FileField(blank=True, help_text='İrsaliye, fatura vb. dökümanları yükleyebilirsiniz', null=True, upload_to='malzeme_gelis_dosyalari/%Y/%m/', verbose_name='Evrak Dosyası'),
        ),
        migrations.AddField(
            model_name='malzemegelis',
            name='para_birimi',
            field=models.CharField(choices=[('TRY', 'Türk Lirası (₺)'), ('USD', 'Amerikan Doları ($)'), ('EUR', 'Euro (€)'), ('GBP', 'İngiliz Sterlini (£)')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='malzemegelis',
            name='toplam_tutar',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Toplam Tutar'),
        ),
    ]
