# Generated by Django 5.2.5 on 2025-08-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_malzemegelis_birim_fiyat_malzemegelis_evrak_dosyasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='malzemegelis',
            name='satis_siparisi',
            field=models.ForeignKey(blank=True, help_text='Bu geliş hangi satış siparişi için', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='malzeme_gelisleri', to='production.siparis', verbose_name='Satış Siparişi'),
        ),
    ]
