# Generated by Django 5.2.5 on 2025-08-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_malzemegelis_satis_siparisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalmasiparisi',
            name='durum',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('kismi', 'Kısmi Teslim'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum'),
        ),
    ]
