# Generated by Django 5.2.5 on 2025-08-21 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_satinalmasiparisi_durum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsIstasyonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='İstasyon Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='İstasyon Adı')),
                ('tip', models.CharField(choices=[('makine', 'Makine'), ('el_iscilik', 'El İşçiliği'), ('montaj', 'Montaj'), ('kalite_kontrol', 'Kalite Kontrol'), ('paketleme', 'Paketleme'), ('depo', 'Depo/Sevkiyat')], max_length=20, verbose_name='İstasyon Tipi')),
                ('durum', models.CharField(choices=[('aktif', 'Aktif'), ('bakim', 'Bakımda'), ('arizali', 'Arızalı'), ('pasif', 'Pasif')], default='aktif', max_length=20, verbose_name='Durum')),
                ('lokasyon', models.CharField(blank=True, max_length=100, verbose_name='Lokasyon/Adres')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('saatlik_kapasite', models.DecimalField(decimal_places=2, default=8.0, help_text='Saatte kaç adet/ürün işlenebilir', max_digits=8, verbose_name='Saatlik Kapasite')),
                ('gunluk_calisma_saati', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Günlük Çalışma Saati')),
                ('saatlik_maliyet', models.DecimalField(decimal_places=2, default=0, help_text='İşçilik + makine maliyeti/saat', max_digits=10, verbose_name='Saatlik Maliyet (TL)')),
                ('gerekli_operator_sayisi', models.PositiveSmallIntegerField(default=1, verbose_name='Gerekli Operatör Sayısı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'İş İstasyonu',
                'verbose_name_plural': 'İş İstasyonları',
                'ordering': ['kod'],
            },
        ),
    ]
