# Generated by Django 5.2.5 on 2025-08-21 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_isistasyonu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsAkisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Akış Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='Akış Adı')),
                ('versiyon', models.CharField(default='1.0', max_length=10, verbose_name='Versiyon')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tip', models.CharField(choices=[('seri', 'Seri İşlem'), ('paralel', 'Paralel İşlem')], default='seri', max_length=10, verbose_name='Akış Tipi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_akislari', to='production.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'İş Akışı',
                'verbose_name_plural': 'İş Akışları',
                'ordering': ['urun', 'kod'],
                'unique_together': {('urun', 'versiyon')},
            },
        ),
        migrations.CreateModel(
            name='IsAkisiOperasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.PositiveSmallIntegerField(verbose_name='Sıra No')),
                ('operasyon_adi', models.CharField(max_length=100, verbose_name='Operasyon Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('standart_sure', models.DecimalField(decimal_places=2, help_text='1 adet için standart işlem süresi', max_digits=8, verbose_name='Standart Süre (dakika)')),
                ('hazirlik_suresi', models.DecimalField(decimal_places=2, default=0, help_text='İş başlangıcında tek seferlik hazırlık süresi', max_digits=8, verbose_name='Hazırlık Süresi (dakika)')),
                ('kalite_kontrolu_gerekli', models.BooleanField(default=False, verbose_name='Kalite Kontrolü Gerekli')),
                ('kritik', models.BooleanField(default=False, help_text='Kritik yol üzerinde mi?', verbose_name='Kritik Operasyon')),
                ('is_akisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operasyonlar', to='production.isakisi', verbose_name='İş Akışı')),
                ('istasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.isistasyonu', verbose_name='İş İstasyonu')),
                ('onceki_operasyonlar', models.ManyToManyField(blank=True, help_text='Bu operasyondan önce tamamlanması gereken operasyonlar', to='production.isakisioperasyon', verbose_name='Önceki Operasyonlar')),
            ],
            options={
                'verbose_name': 'İş Akışı Operasyonu',
                'verbose_name_plural': 'İş Akışı Operasyonları',
                'ordering': ['is_akisi', 'sira_no'],
                'unique_together': {('is_akisi', 'sira_no')},
            },
        ),
    ]
