# Generated by Django 5.2.5 on 2025-08-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_isakisi_isakisioperasyon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsEmri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emirNo', models.CharField(max_length=30, unique=True, verbose_name='İş Emri No')),
                ('planlanan_miktar', models.PositiveIntegerField(verbose_name='Planlanan Miktar')),
                ('uretilen_miktar', models.PositiveIntegerField(default=0, verbose_name='Üretilen Miktar')),
                ('planlanan_baslangic', models.DateTimeField(verbose_name='Planlanan Başlangıç')),
                ('planlanan_bitis', models.DateTimeField(verbose_name='Planlanan Bitiş')),
                ('gercek_baslangic', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç')),
                ('gercek_bitis', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek Bitiş')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandı'), ('basladi', 'Başladı'), ('devam_ediyor', 'Devam Ediyor'), ('beklemede', 'Beklemede'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='planlandi', max_length=20, verbose_name='Durum')),
                ('oncelik', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('notlar', models.TextField(blank=True, verbose_name='Üretim Notları')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_akisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.isakisi', verbose_name='İş Akışı')),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_is_emirleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_emirleri', to='production.siparis', verbose_name='Sipariş')),
                ('siparis_kalemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_emirleri', to='production.sipariskalem', verbose_name='Sipariş Kalemi')),
                ('sorumlu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorumlu_is_emirleri', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'İş Emri',
                'verbose_name_plural': 'İş Emirleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='IsEmriOperasyonDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekleniyor', 'Bekleniyor'), ('basladi', 'Başladı'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('hata', 'Hata'), ('atlandı', 'Atlandı')], default='bekleniyor', max_length=20, verbose_name='Durum')),
                ('baslangic_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Zamanı')),
                ('bitis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('gercek_sure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gerçek Süre (dakika)')),
                ('islenen_miktar', models.PositiveIntegerField(default=0, verbose_name='İşlenen Miktar')),
                ('kalite_onay', models.BooleanField(blank=True, null=True, verbose_name='Kalite Onayı')),
                ('hata_nedeni', models.TextField(blank=True, verbose_name='Hata Nedeni')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operasyon_durumlari', to='production.isemri', verbose_name='İş Emri')),
                ('operasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.isakisioperasyon', verbose_name='Operasyon')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operatör')),
            ],
            options={
                'verbose_name': 'İş Emri Operasyon Durumu',
                'verbose_name_plural': 'İş Emri Operasyon Durumları',
                'ordering': ['is_emri', 'operasyon__sira_no'],
                'unique_together': {('is_emri', 'operasyon')},
            },
        ),
    ]
