# Generated by Django 5.2.5 on 2025-08-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_isemri_isemrioperasyondurum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isistasyonu',
            name='saatlik_kapasite',
        ),
    ]
