# Generated by Django 5.2.5 on 2025-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_remove_isistasyonu_saatlik_kapasite'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardIsAdimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='İş Adımı Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='İş Adımı')),
                ('kategori', models.CharField(choices=[('kesim', 'Kesim İşlemleri'), ('isleme', 'İşleme'), ('montaj', 'Montaj'), ('kalite', 'Kalite Kontrol'), ('paketleme', 'Paketleme'), ('boya', 'Boyama/Kaplama'), ('kaynak', 'Kaynak'), ('tornalama', 'Tornalama'), ('frezeleme', 'Frezeleme'), ('zimpara', 'Zımpara')], max_length=20, verbose_name='Kategori')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tahmini_sure_birim', models.DecimalField(decimal_places=2, help_text='1 adet için ortalama süre', max_digits=8, verbose_name='Tahmini Süre (dk/adet)')),
                ('gerekli_istasyon_tipi', models.CharField(choices=[('makine', 'Makine'), ('el_iscilik', 'El İşçiliği'), ('montaj', 'Montaj'), ('kalite_kontrol', 'Kalite Kontrol'), ('paketleme', 'Paketleme')], max_length=20, verbose_name='Gerekli İstasyon Tipi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('renk', models.CharField(default='#007bff', help_text='Hex renk kodu (örn: #007bff)', max_length=7, verbose_name='Renk Kodu')),
                ('ikon', models.CharField(blank=True, help_text='Örn: fas fa-cut, fas fa-hammer', max_length=50, verbose_name='Font Awesome İkon')),
            ],
            options={
                'verbose_name': 'Standard İş Adımı',
                'verbose_name_plural': 'Standard İş Adımları',
                'ordering': ['kategori', 'ad'],
            },
        ),
        migrations.AlterField(
            model_name='isakisioperasyon',
            name='sira_no',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='Sıra No'),
        ),
    ]
