# Generated by Django 5.2.5 on 2025-08-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_standardisadimi_alter_isakisioperasyon_sira_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isemri',
            name='gercek_baslangic',
        ),
        migrations.RemoveField(
            model_name='isemri',
            name='gercek_bitis',
        ),
        migrations.RemoveField(
            model_name='isemri',
            name='planlanan_baslangic',
        ),
        migrations.RemoveField(
            model_name='isemri',
            name='planlanan_bitis',
        ),
        migrations.AddField(
            model_name='isemri',
            name='ana_emirNo',
            field=models.CharField(default='TEMP', help_text='Bu siparişin tüm operasyonları için ortak numara', max_length=30, verbose_name='Ana İş Emri No'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gercek_baslangic_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç Saati'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gercek_baslangic_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Gerçek Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gercek_bitis_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Gerçek Bitiş Saati'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gercek_bitis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Gerçek Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gercek_sure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Gerçek Süre (dakika)'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gerekli_ara_urunler',
            field=models.JSONField(default=list, help_text='Bu operasyon için gerekli ara ürünler', verbose_name='Gerekli Ara Ürünler'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='gerekli_malzemeler',
            field=models.JSONField(default=list, help_text='Bu operasyon için gerekli malzemeler', verbose_name='Gerekli Malzemeler'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='onceki_operasyonlar',
            field=models.ManyToManyField(blank=True, help_text='Bu operasyondan önce tamamlanması gereken operasyonlar', related_name='sonraki_operasyonlar', to='production.isemri', verbose_name='Önceki Operasyonlar'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='operasyon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.isakisioperasyon', verbose_name='Operasyon'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='planlanan_baslangic_saati',
            field=models.TimeField(default='08:00', verbose_name='Planlanan Başlangıç Saati'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='planlanan_baslangic_tarihi',
            field=models.DateField(default='2024-01-01', verbose_name='Planlanan Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='planlanan_bitis_saati',
            field=models.TimeField(default='17:00', verbose_name='Planlanan Bitiş Saati'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='planlanan_bitis_tarihi',
            field=models.DateField(default='2024-01-01', verbose_name='Planlanan Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='isemri',
            name='planlanan_sure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Planlanan Süre (dakika)'),
        ),
        migrations.AlterField(
            model_name='isemri',
            name='durum',
            field=models.CharField(choices=[('planlandi', 'Planlandı'), ('malzeme_bekliyor', 'Malzeme Bekliyor'), ('ara_urun_bekliyor', 'Ara Ürün Bekliyor'), ('hazir', 'Hazır'), ('basladi', 'Başladı'), ('devam_ediyor', 'Devam Ediyor'), ('beklemede', 'Beklemede'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='planlandi', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='isemri',
            name='emirNo',
            field=models.CharField(max_length=50, unique=True, verbose_name='İş Emri No'),
        ),
        migrations.AlterField(
            model_name='isemri',
            name='planlanan_miktar',
            field=models.PositiveIntegerField(default=1, verbose_name='Planlanan Miktar'),
        ),
        migrations.DeleteModel(
            name='IsEmriOperasyonDurum',
        ),
    ]
