# Generated by Django 5.2.5 on 2025-08-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_remove_isemri_gercek_baslangic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isemri',
            name='siparis_kalemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_emirleri', to='production.sipariskalem', verbose_name='Sipariş Kalemi'),
        ),
    ]
