# Generated by Django 5.2.5 on 2025-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_alter_isemri_siparis_kalemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='isakisioperasyon',
            name='operasyon_ara_urunleri',
            field=models.JSONField(blank=True, default=list, help_text="Bu operasyonda kullanılacak spesifik ara ürünler (BOM'dan seçilen)", verbose_name='Operasyon Ara Ürünleri'),
        ),
        migrations.AddField(
            model_name='isakisioperasyon',
            name='operasyon_malzemeleri',
            field=models.JSONField(blank=True, default=list, help_text="Bu operasyonda kullanılacak spesifik malzemeler (BOM'dan seçilen)", verbose_name='Operasyon Malzemeleri'),
        ),
    ]
