# Generated by Django 5.2.5 on 2025-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_isakisioperasyon_operasyon_ara_urunleri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('malzeme_planlandi', 'Malzeme Planlaması Yapıldı'), ('is_emirleri_olusturuldu', 'İş Emirleri Oluşturuldu'), ('uretimde', 'Üretimde'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='beklemede', max_length=25),
        ),
    ]
