# Generated by Django 5.2.5 on 2025-08-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_siparis_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='isemri',
            name='planlanan_istasyon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.isistasyonu', verbose_name='Planlanan İstasyon'),
        ),
    ]
