# Generated by Django 5.2.5 on 2025-08-22 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_isemri_planlanan_istasyon'),
    ]

    operations = [
        migrations.CreateModel(
            name='UretimPlanlama',
            fields=[
            ],
            options={
                'verbose_name': 'Üretim Planlaması',
                'verbose_name_plural': 'Üretim Planlaması',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('production.isemri',),
        ),
        migrations.AddField(
            model_name='isakisioperasyon',
            name='standart_adim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.standardisadimi', verbose_name='Standart İş Adımı'),
        ),
    ]
