# Generated by Django 5.2.5 on 2025-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_uretimplanlama_isakisioperasyon_standart_adim'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='mikro_fl_kodu',
            field=models.CharField(blank=True, help_text="Mikro FL V17'deki müşteri kodu", max_length=50, null=True, verbose_name='Mikro FL Müşteri Kodu'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='mikro_fl_sync_tarihi',
            field=models.DateTimeField(blank=True, help_text="Mikro FL'den son senkronizasyon tarihi", null=True, verbose_name='Son Senkronizasyon Tarihi'),
        ),
    ]
