# Generated by Django 5.2.5 on 2025-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_musteri_mikro_fl_kodu_musteri_mikro_fl_sync_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musteri',
            name='mikro_fl_kodu',
        ),
        migrations.RemoveField(
            model_name='musteri',
            name='mikro_fl_sync_tarihi',
        ),
        migrations.AddField(
            model_name='musteri',
            name='mikro_fly_kodu',
            field=models.CharField(blank=True, help_text="Mikro Fly V17'deki müşteri kodu", max_length=50, null=True, verbose_name='Mikro Fly Müşteri Kodu'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='mikro_fly_sync_tarihi',
            field=models.DateTimeField(blank=True, help_text="Mikro Fly'den son senkronizasyon tarihi", null=True, verbose_name='Son Senkronizasyon Tarihi'),
        ),
    ]
