# Generated by Django 5.2.5 on 2025-08-23 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_musteri_ulke_siparis_musteri_ulke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='teslim_tarihi',
        ),
        migrations.AddField(
            model_name='sipariskalem',
            name='teslim_tarihi',
            field=models.DateField(default=django.utils.timezone.now, help_text='Bu kalemin teslim tarihi', verbose_name='Teslim Tarihi'),
        ),
    ]
