# Generated by Django 5.2.5 on 2025-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_remove_siparis_teslim_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='mikro_fly_kodu',
            field=models.CharField(blank=True, help_text="Mikro Fly V17'deki stok kodu", max_length=50, null=True, verbose_name='Mikro Fly Stok Kodu'),
        ),
        migrations.AddField(
            model_name='urun',
            name='mikro_fly_sync_tarihi',
            field=models.DateTimeField(blank=True, help_text="Mikro Fly'den son senkronizasyon tarihi", null=True, verbose_name='Son Senkronizasyon Tarihi'),
        ),
    ]
