# Generated by Django 5.2.5 on 2025-08-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_urun_mikro_fly_kodu_urun_mikro_fly_sync_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='maliyet_hesabi',
            field=models.FileField(blank=True, help_text='Maliyet hesap tablosunu yükleyiniz (Zorunlu - Excel, PDF)', null=True, upload_to='siparis_dosyalari/maliyet/%Y/%m/', verbose_name='Maliyet Hesap Tablosu'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='siparis_mektubu',
            field=models.FileField(blank=True, help_text='Sipariş mektubunu yükleyiniz (Zorunlu - PDF, DOC, DOCX)', null=True, upload_to='siparis_dosyalari/mektuplar/%Y/%m/', verbose_name='Sipariş Mektubu'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='dosya',
            field=models.FileField(blank=True, help_text='İsteğe bağlı ek dosya yükleyebilirsiniz', null=True, upload_to='siparis_dosyalari/%Y/%m/', verbose_name='Ek Dosya'),
        ),
    ]
