# Generated by Django 5.2.5 on 2025-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_siparis_maliyet_hesabi_siparis_siparis_mektubu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipariskalem',
            name='birim_fiyat_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD cinsinden birim fiyat (otomatik hesaplanır)', max_digits=15, null=True, verbose_name='Birim Fiyat (USD)'),
        ),
        migrations.AddField(
            model_name='sipariskalem',
            name='doviz',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TRY', 'Turkish Lira'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='sipariskalem',
            name='kur',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='1 birim seçilen para birimi = X USD', max_digits=10, verbose_name='Döviz Kuru'),
        ),
        migrations.AlterField(
            model_name='sipariskalem',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=4, help_text='Seçilen para birimindeki birim fiyat', max_digits=15, verbose_name='Birim Fiyat'),
        ),
    ]
