# Generated by Django 5.2.5 on 2025-08-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_sipariskalem_son_kullanici_ulke'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_tanimi', models.CharField(max_length=200, verbose_name='BOM Tanımı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('malzemeler', models.JSONField(default=list, help_text='Malzeme listesi JSON formatında', verbose_name='Malzemeler')),
                ('eslestirilen_urun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.urun', verbose_name='Eşleştirilen Ürün')),
            ],
            options={
                'verbose_name': 'BOM Template',
                'verbose_name_plural': 'BOM Templates',
                'ordering': ['-guncellenme_tarihi'],
            },
        ),
    ]
